language: python
sudo: false

python:
    - "2.7"
    - "3.6"

matrix:
  include:
    - python: 3.6
      env:
        - STYLE=1
    - python: 3.6
      env:
        - COVERAGE=1

install:
  - pip install pytest pytest-cov coveralls "flake8<3.0" flake8-putty
  - pip install -r requirements.txt
  - python setup.py install

script:
  - |
    if [ "${STYLE}" == "1" ]; then
        flake8 brainconn
    else
        if [ "${COVERAGE}" == "1" ]; then
            TEST_ARGS="--cov-report term-missing --cov=brainconn";
        else
            TEST_ARGS="";
        fi
        py.test ${TEST_ARGS} brainconn;
    fi

after_success:
  - coveralls
